services:
  clueless:
    image: ghcr.io/pxlsspace/clueless:latest
    volumes:
      - ./database.db:/usr/app/src/database/database.db
      - ./resources:/usr/app/resources
    env_file:
      - .env
    command: poetry run python src/main.py
